# Generated by Django 5.0.1 on 2024-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_is_doctor_userprofile_is_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('category', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
